/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kozinkaihatsu.app;

import com.kozinkaihatsu.app.App;

public class AppTest {
     public void appHasAGreeting() {
        App classUnderTest = new App();
       
    }
}